version: '3.8'

services:
  overpass-italy:
    image: gzileni/overpass
    build: ./overpass
    mem_reservation: 2G
    container_name: overpass-italy
    ports:
        - 8083:80

  nominatim:
    container_name: nominatim-italy
    image: gzileni/nominatim
    build: ./nominatim
    restart: always
    mem_reservation: 2G
    ports:
        - "8082:8080"
    environment:
        PBF_PATH: ${PBF_PATH}
        REPLICATION_URL: ${REPLICATION_URL}
        UPDATE_MODE: ${UPDATE_MODE}
    volumes:
        - ./data/nominatim/db:/var/lib/postgresql/14/main
        - ./data/nominatim/osm:/nominatim/data 
    shm_size: 1gb

