version: '3.8'

services:
  overpass-italy:
    image: wiktorn/overpass-api
    mem_reservation: 2G
    restart: always
    container_name: overpass-nord-ovest
    environment:
        OVERPASS_META: ${OVERPASS_META}
        OVERPASS_MODE: ${OVERPASS_MODE}
        OVERPASS_PLANET_URL: ${OVERPASS_PLANET_URL}
        OVERPASS_DIFF_URL: ${OVERPASS_DIFF_URL}
        OVERPASS_RULES_LOAD: ${OVERPASS_RULES_LOAD}
    ports:
        - "8083:80"
    volumes:
        - ./data/overpass:/db

  nominatim:
    container_name: nominatim-nord-ovest
    image: gzileni/nominatim
    build: ./nominatim
    restart: always
    mem_reservation: 2G
    ports:
        - "8082:8080"
    environment:
        PBF_PATH: ${PBF_PATH}
        REPLICATION_URL: ${REPLICATION_URL}
        UPDATE_MODE: ${UPDATE_MODE}
    volumes:
        - ./data/nominatim/db:/var/lib/postgresql/14/main
        - ./data/nominatim/osm:/nominatim/data 
    shm_size: 1gb

