version: "3"

services:
    nominatim:
        container_name: nominatim
        image: mediagis/nominatim:4.1
        restart: always
        ports:
          - "8080:8080"
        environment:
          PBF_URL: ${PBF_URL}
          REPLICATION_URL: ${REPLICATION_URL}
        volumes:
          - ./data/nominatim/db:/var/lib/postgresql/14/main
          - ./data/nominatim/flatnode:/nominatim/flatnode
        shm_size: 1gb

volumes:
    nominatim-data: