# https://github.com/mediagis/nominatim-docker/tree/master/4.1

version: "3.8"

services:
  nominatim:
    container_name: nominatim-italy
    image: mediagis/nominatim:4.1
    restart: always
    ports:
        - "8082:8080"
    environment:
        # see https://github.com/mediagis/nominatim-docker/tree/master/4.1#configuration for more options
        PBF_URL: ${PBF_URL}
        REPLICATION_URL: ${REPLICATION_URL}
        POSTGRES_SHARED_BUFFERS: ${POSTGRES_SHARED_BUFFERS}
        POSTGRES_MAINTENANCE_WORK_MEM: ${POSTGRES_MAINTENANCE_WORK_MEM}
        POSTGRES_AUTOVACUUM_WORK_MEM: ${POSTGRES_AUTOVACUUM_WORK_MEM}
        POSTGRES_WORK_MEM: ${POSTGRES_WORK_MEM}
        POSTGRES_EFFECTIVE_CACHE_SIZE: ${POSTGRES_EFFECTIVE_CACHE_SIZE}
        POSTGRES_SYNCHRONOUS_COMMIT: ${POSTGRES_SYNCHRONOUS_COMMIT}
        POSTGRES_MAX_WAL_SIZE: ${POSTGRES_MAX_WAL_SIZE}
        POSTGRES_CHECKPOINT_TIMEOUT: ${POSTGRES_CHECKPOINT_TIMEOUT}
        POSTGRES_CHECKPOINT_COMPLETION_TARGET: ${POSTGRES_CHECKPOINT_COMPLETION_TARGET}
        IMPORT_STYLE: ${IMPORT_STYLE}
        IMPORT_WIKIPEDIA: ${IMPORT_WIKIPEDIA}
        NOMINATIM_PASSWORD: ${NOMINATIM_PASSWORD}
    volumes:
        - ./data/nominatim/italy:/var/lib/postgresql/14/main
    shm_size: 1gb
    networks:
      - osm-network

networks:
  osm-network:
    driver: bridge
    ipam: 
      driver: default
      config: 
        - subnet: 192.168.191.0/24

volumes:
    nominatim-data: