version: "3"

services:
    nominatim:
        container_name: nominatim-italy
        image: mediagis/nominatim:4.1
        restart: always
        ports:
            - "8080:8080"
        environment:
            # see https://github.com/mediagis/nominatim-docker/tree/master/4.1#configuration for more options
            PBF_URL: http://download.geofabrik.de/europe/italy/nord-ovest-latest.osm.pbf
            REPLICATION_URL: http://download.geofabrik.de/europe/italy/nord-ovest-updates/
        volumes:
            - ./data/nominatim/nord-ovest:/var/lib/postgresql/14/main
        shm_size: 1gb
