FROM wiktorn/overpass-api

WORKDIR /db
# RUN wget -O planet.osm.bz2 "https://download.geofabrik.de/europe/italy-latest.osm.bz2"
RUN wget -O planet.osm.bz2 "http://download.geofabrik.de/europe/italy/nord-ovest-latest.osm.bz2"